codemood/badges/urls.py
from django.conf.urls import patterns, url

from .views import BadgeUserList


urlpatterns = patterns('',
    url(r'^$', BadgeUserList.as_view(), name='list'),
)

codemood/codemood/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'', include('common.urls')),
    url(r'^badges/', include('badges.urls', namespace='badges')),

    url(r'', include('social_auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns("django.views",
        url(r"%s(?P<path>.*)$" % settings.STATIC_URL[1:], "static.serve", {
            "document_root": settings.STATIC_ROOT,
            'show_indexes': True,
        }),
        url(r"%s(?P<path>.*)$" % settings.MEDIA_URL[1:], "static.serve", {
            "document_root": settings.MEDIA_ROOT,
            'show_indexes': True,
        }),
    )

codemood/templates/base-authorized.html
{% extends 'base.html' %}
{% load gravatar %}



{% block body %}
  <div class="masthead">
    <div class="pull-right gravatar" style="background-image:url('{% gravatar_for_user request.user 100 %}');"></div>
    <h3 class="muted">Codingmood</h3>
  </div>

  <hr>

  <div class="row-fluid">
    <div class="col-md-4">
      <div class="well" style="max-width: 340px; padding: 8px 0;">
        <ul class="nav nav-list">
          <li><a href="/">Home</a></li>
          <li><a href="{% url 'badges:list' %}">Badges</a></li>
        </ul>
      </div>
      {% block left-side %}{% endblock %}
    </div>

    {% block container %}{% endblock %}
  </div>
{% endblock %}

codemood/templates/base-not-authorized.html
{% extends 'base.html' %}


{% block body %}
  <div class="masthead">
    <h3 class="muted">Codingmood</h3>
  </div>

  <hr>

  <div class="jumbotron">
    {% block container %}{% endblock %}
  </div>
{% endblock %}

codemood/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Codingmood{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="{% static 'css/flat-ui.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">


    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="{% static 'js/html5shiv.js' %}"></script>
    <![endif]-->
    {% block head %}{% endblock %}
  </head>
  <body>

    <div class="container-fluid">
      {% block body %}
      {% endblock %}
    </div>

    <!-- Load JS here for greater good =============================-->
    <script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui-1.10.3.custom.min.js' %}"></script>
    <script src="{% static 'js/jquery.ui.touch-punch.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.js' %}"></script>
    <script src="{% static 'js/bootstrap-switch.js' %}"></script>
    <script src="{% static 'js/flatui-checkbox.js' %}"></script>
    <script src="{% static 'js/flatui-radio.js' %}"></script>
    <script src="{% static 'js/jquery.tagsinput.js' %}"></script>
    <script src="{% static 'js/jquery.placeholder.js' %}"></script>
  </body>
</html>